export const COUNTRIES = [
  { code: "+93", name: "Afghanistan", length: 9 },
  { code: "+355", name: "Albania", length: 9 },
  { code: "+213", name: "Algeria", length: 9 },
  { code: "+376", name: "Andorra", length: 6 },
  { code: "+244", name: "Angola", length: 9 },
  { code: "+54", name: "Argentina", length: 10 },
  { code: "+374", name: "Armenia", length: 8 },
  { code: "+61", name: "Australia", length: 9 },
  { code: "+43", name: "Austria", length: 10 },
  { code: "+994", name: "Azerbaijan", length: 9 },
  { code: "+973", name: "Bahrain", length: 8 },
  { code: "+880", name: "Bangladesh", length: 10 },
  { code: "+375", name: "Belarus", length: 9 },
  { code: "+32", name: "Belgium", length: 9 },
  { code: "+501", name: "Belize", length: 7 },
  { code: "+229", name: "Benin", length: 8 },
  { code: "+975", name: "Bhutan", length: 8 },
  { code: "+591", name: "Bolivia", length: 8 },
  { code: "+387", name: "Bosnia and Herzegovina", length: 8 },
  { code: "+267", name: "Botswana", length: 8 },
  { code: "+55", name: "Brazil", length: 11 },
  { code: "+673", name: "Brunei", length: 7 },
  { code: "+359", name: "Bulgaria", length: 9 },
  { code: "+226", name: "Burkina Faso", length: 8 },
  { code: "+257", name: "Burundi", length: 8 },
  { code: "+855", name: "Cambodia", length: 9 },
  { code: "+237", name: "Cameroon", length: 9 },
  { code: "+1", name: "Canada", length: 10 },
  { code: "+238", name: "Cape Verde", length: 7 },
  { code: "+236", name: "Central African Republic", length: 8 },
  { code: "+235", name: "Chad", length: 8 },
  { code: "+56", name: "Chile", length: 9 },
  { code: "+86", name: "China", length: 11 },
  { code: "+57", name: "Colombia", length: 10 },
  { code: "+269", name: "Comoros", length: 7 },
  { code: "+242", name: "Congo", length: 9 },
  { code: "+506", name: "Costa Rica", length: 8 },
  { code: "+385", name: "Croatia", length: 9 },
  { code: "+53", name: "Cuba", length: 8 },
  { code: "+357", name: "Cyprus", length: 8 },
  { code: "+420", name: "Czech Republic", length: 9 },
  { code: "+45", name: "Denmark", length: 8 },
  { code: "+253", name: "Djibouti", length: 8 },
  { code: "+593", name: "Ecuador", length: 9 },
  { code: "+20", name: "Egypt", length: 10 },
  { code: "+503", name: "El Salvador", length: 8 },
  { code: "+240", name: "Equatorial Guinea", length: 9 },
  { code: "+291", name: "Eritrea", length: 7 },
  { code: "+372", name: "Estonia", length: 8 },
  { code: "+251", name: "Ethiopia", length: 9 },
  { code: "+679", name: "Fiji", length: 7 },
  { code: "+358", name: "Finland", length: 10 },
  { code: "+33", name: "France", length: 9 },
  { code: "+241", name: "Gabon", length: 7 },
  { code: "+220", name: "Gambia", length: 7 },
  { code: "+995", name: "Georgia", length: 9 },
  { code: "+49", name: "Germany", length: 10 },
  { code: "+233", name: "Ghana", length: 9 },
  { code: "+30", name: "Greece", length: 10 },
  { code: "+502", name: "Guatemala", length: 8 },
  { code: "+224", name: "Guinea", length: 9 },
  { code: "+245", name: "Guinea-Bissau", length: 7 },
  { code: "+592", name: "Guyana", length: 7 },
  { code: "+509", name: "Haiti", length: 8 },
  { code: "+504", name: "Honduras", length: 8 },
  { code: "+852", name: "Hong Kong", length: 8 },
  { code: "+36", name: "Hungary", length: 9 },
  { code: "+354", name: "Iceland", length: 7 },
  { code: "+91", name: "India", length: 10 },
  { code: "+62", name: "Indonesia", length: 11 },
  { code: "+98", name: "Iran", length: 10 },
  { code: "+964", name: "Iraq", length: 10 },
  { code: "+353", name: "Ireland", length: 9 },
  { code: "+972", name: "Israel", length: 9 },
  { code: "+39", name: "Italy", length: 10 },
  { code: "+225", name: "Ivory Coast", length: 10 },
  { code: "+81", name: "Japan", length: 10 },
  { code: "+962", name: "Jordan", length: 9 },
  { code: "+7", name: "Kazakhstan", length: 10 },
  { code: "+254", name: "Kenya", length: 10 },
  { code: "+965", name: "Kuwait", length: 8 },
  { code: "+996", name: "Kyrgyzstan", length: 9 },
  { code: "+856", name: "Laos", length: 10 },
  { code: "+371", name: "Latvia", length: 8 },
  { code: "+961", name: "Lebanon", length: 8 },
  { code: "+266", name: "Lesotho", length: 8 },
  { code: "+231", name: "Liberia", length: 8 },
  { code: "+218", name: "Libya", length: 10 },
  { code: "+423", name: "Liechtenstein", length: 7 },
  { code: "+370", name: "Lithuania", length: 8 },
  { code: "+352", name: "Luxembourg", length: 9 },
  { code: "+853", name: "Macau", length: 8 },
  { code: "+389", name: "Macedonia", length: 8 },
  { code: "+261", name: "Madagascar", length: 9 },
  { code: "+265", name: "Malawi", length: 9 },
  { code: "+60", name: "Malaysia", length: 10 },
  { code: "+960", name: "Maldives", length: 7 },
  { code: "+223", name: "Mali", length: 8 },
  { code: "+356", name: "Malta", length: 8 },
  { code: "+222", name: "Mauritania", length: 8 },
  { code: "+230", name: "Mauritius", length: 8 },
  { code: "+52", name: "Mexico", length: 10 },
  { code: "+373", name: "Moldova", length: 8 },
  { code: "+377", name: "Monaco", length: 8 },
  { code: "+976", name: "Mongolia", length: 8 },
  { code: "+382", name: "Montenegro", length: 8 },
  { code: "+212", name: "Morocco", length: 9 },
  { code: "+258", name: "Mozambique", length: 9 },
  { code: "+95", name: "Myanmar", length: 9 },
  { code: "+264", name: "Namibia", length: 9 },
  { code: "+977", name: "Nepal", length: 10 },
  { code: "+31", name: "Netherlands", length: 9 },
  { code: "+64", name: "New Zealand", length: 9 },
  { code: "+505", name: "Nicaragua", length: 8 },
  { code: "+227", name: "Niger", length: 8 },
  { code: "+234", name: "Nigeria", length: 10 },
  { code: "+47", name: "Norway", length: 8 },
  { code: "+968", name: "Oman", length: 8 },
  { code: "+92", name: "Pakistan", length: 10 },
  { code: "+970", name: "Palestine", length: 9 },
  { code: "+507", name: "Panama", length: 8 },
  { code: "+675", name: "Papua New Guinea", length: 8 },
  { code: "+595", name: "Paraguay", length: 9 },
  { code: "+51", name: "Peru", length: 9 },
  { code: "+63", name: "Philippines", length: 10 },
  { code: "+48", name: "Poland", length: 9 },
  { code: "+351", name: "Portugal", length: 9 },
  { code: "+974", name: "Qatar", length: 8 },
  { code: "+40", name: "Romania", length: 10 },
  { code: "+7", name: "Russia", length: 10 },
  { code: "+250", name: "Rwanda", length: 9 },
  { code: "+966", name: "Saudi Arabia", length: 9 },
  { code: "+221", name: "Senegal", length: 9 },
  { code: "+381", name: "Serbia", length: 9 },
  { code: "+248", name: "Seychelles", length: 7 },
  { code: "+232", name: "Sierra Leone", length: 8 },
  { code: "+65", name: "Singapore", length: 8 },
  { code: "+421", name: "Slovakia", length: 9 },
  { code: "+386", name: "Slovenia", length: 8 },
  { code: "+252", name: "Somalia", length: 8 },
  { code: "+27", name: "South Africa", length: 9 },
  { code: "+82", name: "South Korea", length: 10 },
  { code: "+211", name: "South Sudan", length: 9 },
  { code: "+34", name: "Spain", length: 9 },
  { code: "+94", name: "Sri Lanka", length: 9 },
  { code: "+249", name: "Sudan", length: 9 },
  { code: "+597", name: "Suriname", length: 7 },
  { code: "+268", name: "Swaziland", length: 8 },
  { code: "+46", name: "Sweden", length: 9 },
  { code: "+41", name: "Switzerland", length: 9 },
  { code: "+963", name: "Syria", length: 9 },
  { code: "+886", name: "Taiwan", length: 9 },
  { code: "+992", name: "Tajikistan", length: 9 },
  { code: "+255", name: "Tanzania", length: 9 },
  { code: "+66", name: "Thailand", length: 9 },
  { code: "+228", name: "Togo", length: 8 },
  { code: "+216", name: "Tunisia", length: 8 },
  { code: "+90", name: "Turkey", length: 10 },
  { code: "+993", name: "Turkmenistan", length: 8 },
  { code: "+256", name: "Uganda", length: 9 },
  { code: "+380", name: "Ukraine", length: 9 },
  { code: "+971", name: "United Arab Emirates", length: 9 },
  { code: "+44", name: "United Kingdom", length: 10 },
  { code: "+1", name: "United States", length: 10 },
  { code: "+598", name: "Uruguay", length: 8 },
  { code: "+998", name: "Uzbekistan", length: 9 },
  { code: "+58", name: "Venezuela", length: 10 },
  { code: "+84", name: "Vietnam", length: 9 },
  { code: "+967", name: "Yemen", length: 9 },
  { code: "+260", name: "Zambia", length: 9 },
  { code: "+263", name: "Zimbabwe", length: 9 },
];
